### PR TITLE
Better method to download drivers

### PR DESCRIPTION
**Pull request by ruescar**

### CODE REVIEW

**Comment by ruescar** [comment]
All changes tested successfully.

**Comment by vania-pooh** [comment]
@ruescar let's add `jq` to the list of required binaries: https://github.com/aerokube/moon-deploy/blob/master/moon.yaml#L174-L176 In that case if jq is missing script fill fail at the beginning.

**Comment by ruescar** [comment]
@vania-pooh I'm sure that's a simple change, but I'm not that familiar with that repo. Would you mind doing that change yourself?

**Comment by vania-pooh** [comment]
@ruescar that was copy-paste error. I was speaking about these lines: https://github.com/aerokube/selenoid-images/blob/09300f733f56bdb2bc57eb983c318305c8ca615e/selenium/automate_android.sh#L133-L139

**Comment by ruescar** [comment]
@vania-pooh Got it. Do you mean to add the `require_command` in `build.sh` or on each of the `automate_browser.sh`?

**Comment by vania-pooh** [comment]
@ruescar let's add to `automate_*.sh` scripts, otherwise they will fail after working some time.

**Comment by vania-pooh** [comment]
@ruescar thank you for contribution!

**Pull request merged**
