### PR TITLE
Added support for browsers Beta and Dev channels

### PR DESCRIPTION
**Pull request by ruescar**
selenoid-container-tests passed for latest versions of all combinations of browsers (Firefox, Chrome, Opera, Yandex), channels (Stable, Beta, Dev), methods (apt, local), and OS (Ubuntu, Mac):

#### APT ####
./automate_firefox.sh 70.0.1+build1-0ubuntu0.18.04.1 1.9.3 70.0 0.26.0
./automate_chrome.sh 78.0.3904.108-1 78.0.3904.70 78.0
./automate_opera.sh 65.0.3467.42 78.0.3904.87 65.0
./automate_yandex.sh 19.9.3.358-1 19.9.3 19.9
#### LOCAL ####
./automate_firefox.sh firefox_70.0.1+build1-0ubuntu0.18.04.1_amd64.deb 1.9.3 70.0 0.26.0
./automate_firefox.sh firefox_70.0.1+build1-0ubuntu0.18.04.1_i386.deb 1.9.3 70.0 0.26.0
./automate_chrome.sh google-chrome-stable_78.0.3904.108-1_amd64.deb 78.0.3904.70 78.0
./automate_opera.sh opera-stable_65.0.3467.42_amd64.deb 78.0.3904.87 65.0
./automate_yandex.sh yandex-browser-beta_19.9.3.358-1_amd64.deb 19.9.3 19.9

#### APT ####
./automate_firefox.sh 71.0~b11+build1-0ubuntu0.18.04.1 1.9.3 71.0 0.26.0 beta
./automate_chrome.sh 79.0.3945.36-1 79.0.3945.16 79.0 beta
./automate_opera.sh 65.0.3467.32 78.0.3904.87 65.0 beta
#### LOCAL ####
./automate_firefox.sh firefox_71.0_b11+build1-0ubuntu0.18.04.1_amd64.deb 1.9.3 71.0 0.26.0 beta
./automate_firefox.sh firefox_71.0_b11+build1-0ubuntu0.18.04.1_i386.deb 1.9.3 71.0 0.26.0 beta
./automate_chrome.sh google-chrome-beta_79.0.3945.36-1_amd64.deb 79.0.3945.16 79.0 beta
./automate_opera.sh opera-beta_65.0.3467.32_amd64.deb 78.0.3904.87 65.0 beta

#### APT ####
./automate_firefox.sh 72.0~a1~hg20191114r501767-0ubuntu0.18.04.1~umd1 1.9.3 72.0 0.26.0 dev
./automate_chrome.sh 80.0.3964.0-1 79.0.3945.16 80.0 dev
./automate_opera.sh 66.0.3502.0 78.0.3904.87 66.0 dev
#### LOCAL ####
./automate_firefox.sh firefox-trunk_72.0_a1_hg20191114r501767-0ubuntu0.18.04.1_umd1_amd64.deb 1.9.3 72.0 0.26.0 dev
./automate_firefox.sh firefox-trunk_72.0_a1_hg20191114r501767-0ubuntu0.18.04.1_umd1_i386.deb 1.9.3 72.0 0.26.0 dev
./automate_chrome.sh google-chrome-unstable_80.0.3964.0-1_amd64.deb 79.0.3945.16 80.0 dev
./automate_opera.sh opera-developer_66.0.3502.0_amd64.deb 78.0.3904.87 66.0 dev

### CODE REVIEW

**Comment by vania-pooh** [comment]
@ruescar thank you for contribution. We are going to use all this stuff to build images automatically with our CI.

**Comment by Jisho23** [comment]
I'm having issues when trying to run the automate throws the following error: `E: Version '79.0.3945.36-1' for 'google-chrome-beta' was not found`. Am I missing something?

**Comment by vania-pooh** [comment]
@Jisho23 we did not yet finished setting up our CI, so proably @ruescar could help here.

**Comment by ruescar** [comment]
@Jisho23 @vania-pooh The package versions I posted, were the latest ones back then, but you should use the latest versions, because companies usually only keep published their latest versions of each browser package. And Beta or Dev channels change more often, hence why you didn't see Stable channel failing. To keep it easy, I recommend you check latest versions on UbuntuUpdates (i.e https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-beta)
And then use the latest version of the corresponding driver. With the exception of ChromeDriver, which has specific version selection rules:
http://chromedriver.chromium.org/downloads/version-selection

**Comment by Jisho23** [comment]
Hi I appreciate you getting back. I guess I'm just very confused on how I set up the chrome image, even when referencing the latest version and driver (the command I'm using is `./automate_chrome.sh google-chrome-beta+79.0.3945.74-1_amd64.deb 79.0.3945.74 79.0b beta`) I receive similar 404 errors. Is there a step I am missing or not finding the right version + driver combo?

**Comment by ruescar** [comment]
@Jisho23 You are passing an incorrect ChromeDriver version. It's similar to Chrome's version, but it's not the same one (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_79.0.3945). So, example of correct commands could be:
`./automate_chrome.sh 79.0.3945.74-1 79.0.3945.36 79.0b beta
./automate_chrome.sh google-chrome-beta+79.0.3945.74-1_amd64.deb 79.0.3945.36 79.0b beta`

**Comment by yevhen-laichenkov** [comment]
Hey @vania-pooh 
Do you have any plans to add this feature?

**Comment by ruescar** [comment]
@yevhen-laichenkov In the meantime, feel free to use https://hub.docker.com/r/twilio/selenoid where we publish latest Dev and Beta images for Chrome and Firefox.

**Comment by yevhen-laichenkov** [comment]
Hey @ruescar 
Thanks for the reply!
I'll try it.

**Pull request merged**
