### PR TITLE
firefox-esr support for automate_firefox.sh

### PR DESCRIPTION
**Pull request by gogro**
now possible : ./automate_firefox.sh 68.10.0esr+build1-0ubuntu0.18.04.1 latest 68-esr 0.26.0 esr
i can add changes to readme if you approve in general
1 failed test :
image

### CODE REVIEW

**Comment by vania-pooh** [comment]
@gogro thank you for contribution!

**Comment by ruescar** [comment]
@gogro Tests should pass using their latest version. On the other hand, I committed minor changes missing from this PR.

**Comment by vania-pooh** [comment]
@gogro btw, failed test is because of Java 9 XML changes.

**Comment by ruescar** [comment]
True. In the past I also had issues with the tests because I was running them with Java 11. With Java 8 they should work well. Maybe we should add that info to the README.

**Pull request merged**
