### PR TITLE
Quicktime compatible pixelformat on videos

### PR DESCRIPTION
**Pull request by presidenten**
This flag makes videos quickviewable on mac and viewable on ios devices

### CODE REVIEW

**Comment by vania-pooh** [comment]
Omg, how did you find this? :)

**Comment by vania-pooh** [comment]
Will try to rebuild image tomorrow.

**Comment by presidenten** [comment]
I remembered that I saw a comment about it in the source code of a github project that records testcases in Nightwatch.js, when I rewrote it for Webdriver.io to have recordings on the local machine when developing tests.
So I added it to the selenoid video api and it worked great! And then I though we might as well have it in the official video recorder as well :)

**Comment by vania-pooh** [comment]
@presidenten sure, really good improvement.

**Pull request merged**
