### PR TITLE
Add new dependencies to Android docker file

### PR DESCRIPTION
**Pull request by katanaBoy**
New dependencies added to resolve libX* failures

### CODE REVIEW

**Comment by vania-pooh** [comment]
@katanaBoy could you try with this smaller subset of packages?
```
	    libxcomposite1 \
	    libxcursor1 \
	    libxi6 \
	    libasound2 \
```
It seems that these 4 packages should be sufficient.

**Comment by katanaBoy** [comment]
Sure I'll try the smaller subset and we'll see what will be the result.

**Comment by katanaBoy** [comment]
You are right I lowered the amount of dependencies.

**Comment by vania-pooh** [comment]
@katanaBoy thank you for contribution!

**Pull request merged**
