### PR TITLE
Added iproute2 Linux utils to Firefox.

### PR DESCRIPTION
**Pull request by merinsTDL**
Chrome and Firefox images were successfully tested with selenoid-container-tests passing.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@merinsTDL what is the use case? In case of Chrome we need this package to get `ip` command availabe.

**Comment by merinsTDL** [comment]
The PR was added due to the consistency between Chrome and Firefox browsers used in advanced network scenarios, where the tests rely on command for network configuration (ip) and included traffic control package (tc) for network chaos simulation.

**Comment by vania-pooh** [comment]
@merinsTDL I still don't get how browser would interact with `ip` or `tc` command. Are you using these images without Selenoid?

**Comment by merinsTDL** [comment]
The iproute2 utils are used browser-images with Selenoid. And the extended use-case is to target Selenoid "network" labelled browser containers after they are launched with network chaos tools and reduce the network condition setup time if the iproute2 is pre-bundled.

**Comment by vania-pooh** [comment]
@merinsTDL ok, I don't see any usage of installed package in `entrypoint.sh`. Anyway let's merge this if you need it. :)

**Pull request merged**
