### PR TITLE
Added support for yandex browser via opera driver

### PR DESCRIPTION
**Pull request by zarom**

### CODE REVIEW

**Comment by vania-pooh** [comment]
@Zarom did you test images with the following tests? http://github.com/aerokube/selenoid-container-tests

**Comment by Zarom** [comment]
@vania-pooh not yet. Will come back with results.

**Comment by Zarom** [comment]
@vania-pooh got some troubles while getting tests running on our machines... All tests passes, except "TestProxy":
```
Results :

Failed tests:
  TestProxy.testProxy:46
Expected: is not an empty collection
     but: was <[]>

Tests run: 22, Failures: 1, Errors: 0, Skipped: 1
```

Because it fails even on selenoid/opera image, I think this is driver or container test issue.

**Comment by vania-pooh** [comment]
@Zarom ok, please squash your commits and I'll merge.

**Comment by zarom** [comment]
@vania-pooh done!

**Comment by vania-pooh** [comment]
@zarom thank you for contribution!

**Pull request merged**
